export enum Routes {
    HOME = '/',
    PRODUCTS = '/products',
    SIZES_GUIDE = '/sizes-guide',
    FAVORITES = '/favorites',
    CART = '/cart',
    SIGNIN = '/signin',
    SIGNUP = '/signup',
    RESTORE_PASSWORD = '/restore-password',
    VERIFY = '/verify',
    SHIPPING = '/shipping',
    PAYMENT = '/payment',
    PLACEORDER = '/placeorder',
    ORDER = '/order',
    ORDER_HISTORY = '/orderhistory',
    DASHBOARD = '/dashboard',
    DASHBOARD_ORDERS = '/dashboard/orders',
    DASHBOARD_PRODUCTS = '/dashboard/products',
    DASHBOARD_PRODUCTS_CREATE = '/dashboard/products/create-product',
    DASHBOARD_PRODUCTS_UPDATE = '/dashboard/products/update-product',
    DASHBOARD_USERS = '/dashboard/users',
    DASHBOARD_USERS_UPDATE = '/dashboard/users/update-user',
}